adoptame/adoptame/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from core.views import index, contact

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('', include('core.urls')),
    path('pets/', include('pet.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('chat/', include('chat.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

adoptame/chat/urls.py
from django.urls import path
from . import views

app_name='chat'
urlpatterns = [
    path('', views.inbox, name='inbox'),
    path('<int:pk>/', views.detail, name='detail'),
    path('new/<int:pet_pk>/', views.new_chat, name='new'),
]

adoptame/pet/urls.py
from django.urls import path
from . import views

app_name = 'pet'

urlpatterns = [
    path('', views.pets, name='pets'),
    path('new/', views.new, name='new'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),
    path('get-races/', views.get_races, name='getRaces'),
]

adoptame/pet/models.py
from django.db import models
from user.models import PetOwner as User

class Specie(models.Model):
    name = models.CharField(max_length=100)

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return self.name


class Race(models.Model):
    name = models.CharField("Raza", max_length=50)
    specie = models.ForeignKey(Specie, on_delete=models.CASCADE)

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return self.name


class Pet(models.Model):
    name = models.CharField('Name of the pet',  max_length=50)
    age = models.IntegerField('Age in years', default=0)
    description = models.TextField('General description', blank=True, null=True)
    adopted = models.BooleanField('Is adopted?', default=False)
    create_at = models.DateField(auto_now_add=True)
    created_by = models.ForeignKey(User, verbose_name="Owner", related_name='pets', on_delete=models.CASCADE)
    specie = models.ForeignKey(Specie, related_name='pets', verbose_name="Pet's specie", on_delete=models.CASCADE)
    race = models.ForeignKey(Race, related_name='pets', verbose_name="Pet's race",blank=True, null=True, on_delete=models.SET_NULL)
    image = models.ImageField(upload_to='pet_images', blank=True, null=True)

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return self.name

adoptame/pet/forms.py
from django import forms
from .models import Pet, Race

INPUT_CLASSES = 'w-75 py-2 px-3 rounded border bg-white'
FORM_CONTROL = INPUT_CLASSES + ' form-control'
FORM_SELECT = INPUT_CLASSES + ' form-select selectpicker'

class NewPetForm(forms.ModelForm):
    class Meta:
        model = Pet
        fields = ('specie', 'race', 'name', 'description', 'image', 'age')
        labels = {
            'specie': 'Especie',
            'race':'Raza',
            'name':'Nombre',
            'description':'Descripcion',
            'image':'Foto',
            'age':'Edad',
            }

        widgets = {
            'specie': forms.Select(attrs={
                'class': FORM_SELECT,
            }),
            'race': forms.Select(attrs={
                'class': FORM_SELECT,
                'data-live-search': 'true',
            }),
            'name': forms.TextInput(attrs={
                'class': FORM_CONTROL,
            }),
            'description': forms.Textarea(attrs={
                'class': FORM_CONTROL,
            }),
            'age': forms.NumberInput(attrs={
                'class': FORM_CONTROL,
            }),
            'image': forms.FileInput(attrs={
                'class': FORM_CONTROL,
            }),
        }

class EditPetForm(forms.ModelForm):
    class Meta:
        model = Pet
        fields = ('race', 'name', 'description', 'image', 'age', 'adopted')
        labels = {
            'race':'Raza',
            'name':'Nombre',
            'description':'Descripcion',
            'image':'Foto',
            'age':'Edad',
            'adopted': 'Adoptado'
            }

        widgets = {
            'race': forms.Select(attrs={
                'class': FORM_SELECT,
                'data-live-search': 'true',
            }),
            'name': forms.TextInput(attrs={
                'class': FORM_CONTROL,
            }),
            'description': forms.Textarea(attrs={
                'class': FORM_CONTROL,
            }),
            'age': forms.NumberInput(attrs={
                'class': FORM_CONTROL,
            }),
            'image': forms.FileInput(attrs={
                'class': FORM_CONTROL,
            }),
        }

adoptame/pet/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.http import JsonResponse
from .forms import NewPetForm, EditPetForm
from django.db.models import Q
from .models import Pet, Specie, Race

def pets(request):
    query = request.GET.get('query','')
    maxAge = request.GET.get('maxAge', 20)
    specie_id = request.GET.get('specie', 0)
    race_id = request.GET.get('race', 0)
    species = Specie.objects.all()
    races = Race.objects.all()
    pets = Pet.objects.filter(adopted=False)

    if query:
        pets = pets.filter(Q(name__icontains=query) | Q(description__icontains=query))

    if specie_id:
        pets = pets.filter(specie_id=specie_id)

    if race_id:
        pets = pets.filter(race_id=race_id)

    pets = pets.filter(age__lte=maxAge)

    return render(request, 'pet/pets.html', {
        'pets':pets,
        'query':query,
        'maxAge': int(maxAge),
        'species': species,
        'specie_id': int(specie_id),
        'races': races,
        'race_id': int(race_id)
    })

def detail(request, pk):
    pet = get_object_or_404(Pet, pk=pk)
    context = {'pet': pet}

    return render(request, 'pet/detail.html', context)

@login_required
def new(request):
    if request.method == 'POST':
        form = NewPetForm(request.POST, request.FILES)

        if form.is_valid():
            pet = form.save(commit=False)
            pet.created_by = request.user
            pet.save()

            return redirect('pet:detail', pk=pet.id)
    else:
        form = NewPetForm()

    return render(request, 'pet/form.html', {'form': form, 'title': 'Tu nueva mascota'})


@login_required
def edit(request, pk):
    pet = get_object_or_404(Pet, pk=pk, created_by=request.user)

    if request.method == 'POST':
        form = EditPetForm(request.POST, request.FILES, instance=pet)

        if form.is_valid():
            form.save()

            return redirect('pet:detail', pk=pet.id)
    else:
        form = EditPetForm(instance=pet)

    return render(request, 'pet/form.html', {'form': form, 'title': 'Edita tu mascota'})

@login_required
def delete(request, pk):
    pet = get_object_or_404(Pet, pk=pk, created_by=request.user)
    pet.delete()

    return redirect('dashboard:index')

def get_races(request):
    specie_id = request.GET.get('specie')
    races = Race.objects.filter(specie=specie_id).order_by('name')

    response_data = {
        "races": list(races)
    }

    return JsonResponse(response_data)

adoptame/pet/templates/pet/detail.html
{% extends "core/base.html" %}

{% block title %}{{ pet.name }}{% endblock title %}

{% block content %}
<div class="container">
    <div class="row">
      <div class="col-6">
        {% if pet.image %}
        <img src="{{ pet.image.url }}" width="100%" height="auto" class="rounded" alt="{{ pet.name }}">
        {% else %}
        <img src="/media/resources/no_image.jpg" width="100%" height="auto" class="rounded" alt="{{ pet.name }}">
        {% endif %}
      </div>
      <div class="col-6 bg-light rounded">
        <h1>{{ pet.name }}</h1>
        {% if pet.description %}<p><strong>Descripcion:</strong> {{ pet.description }}</p>{% endif %}
        <p class="text-secondary"><strong>Propietario:</strong> {{ pet.created_by }}</p>
        <p class="text-secondary"><strong>Edad:</strong> {{ pet.age }} año/s</p>
        {% if pet.race %}<p class="text-secondary"><strong>Raza:</strong> {{ pet.race }}</p>{% endif %}

        {% if request.user == pet.created_by %}
        <div class="card border-danger" style="width: 18rem;">
          <div class="card-body">
            <p class="card-text"> Eres el propietario de esta mascota </p>
            <a href="{% url 'pet:edit' pet.id %}" class="btn btn-success">Editar</a>
            <a href="{% url 'pet:delete' pet.id %}" class="btn btn-danger">Borrar Mascota</a>
          </div>
        </div>
        {% else %}
        <a href="{% url 'chat:new' pet.id %}" class="btn btn-primary">Contactar</a>
        {% endif %}
      </div>
    </div>
  </div>
{% endblock content %}

adoptame/pet/templates/pet/form.html
{% extends "core/base.html" %}

{% block title %}{{ title }}{% endblock title %}

{% block content %}
<h1 class="mb-3">{{ title }}</h1>

<form method="post" action="." enctype="multipart/form-data">
    {% csrf_token %}
    <div class="py-2 form-group">
        {{ form.as_p }}
    </div>
    {% if form.errors or form.non_field_erros %}
        <div class="mb-2 p-3 bg-error rounded-3">
            {% for field in form %}
                {{ field.errors }}
            {% endfor %}
            {{ form.non_field_erros }}
        </div>
    {% endif %}
    <button class="btn btn-primary px-4 py-3">Agregar mascota</button>
</form>
{% endblock content %}

adoptame/pet/templates/pet/pets.html
{% extends "core/base.html" %}

{% block title %} Mascotas {% endblock title %}

{% block content %}
    <div class="row px-3">
        <div class="col col-2 bg-white rounded">
            <form class="form-control mt-2" method="get" action="{% url 'pet:pets' %}">
                <div class="form-group">
                    <input name="query" class="w-100 form-text rounded" type="text" value="{{ query }}" placeholder="Encuentra tu nueva mascota"/>
                </div>
                <div class="form-group mt-4">
                    <label for="maxAge" class="form-label mt-2">Edad Maxima: </label><output>{% if maxAge %} {{ maxAge }} {% else %} 20 {% endif %}</output>
                    <input type="range" class="form-range" id="maxAge" name="maxAge" min=0 max=20 value={% if maxAge %} {{ maxAge }} {% else %} 20 {% endif %} oninput="this.previousElementSibling.value = this.value">
                </div>

                    <button class="btn btn-secondary btn-sm mt-2">Buscar</button>
            </form>

            <div class="container mt-4">
                <h2>Especies</h2>
                <div class="list-group">
                    {% for specie in species %}
                    <a class="list-group-item {% if specie.id == specie_id %} active {% endif %}" href="{% url 'pet:pets' %}?query={{ query }}&specie={{ specie.id }}{% if race %}&race={{ race_id }}{% endif %}"> {{ specie.name }}</a>
                    {% endfor %}
                </div>

                <h2>Razas</h2>
                <div class="list-group">
                    {% for race in races %}
                    <a class="list-group-item {% if race.id == race_id %} active {% endif %}" href="{% url 'pet:pets' %}?query={{ query }}{% if specie_id %}&specie={{ specie_id }}{% endif %}&race={{ race.id }}"> {{ race.name }}</a>
                    {% endfor %}
                </div>

              <a href="{% url 'pet:pets' %}" class="btn btn-warning mt-4">Limpiar filtros</a>
            </div>
        </div>
        <div class="col col-10">
            <div class="row bg-light">
                {% for pet in pets %}
                    <a href="{% url 'pet:detail' pet.id %}" class="col col-sm-4 mb-2 text-decoration-none text-reset">
                        <div class="card">
                                {% if pet.image %}
                                    <img src="{{ pet.image.url }}" class="card-img-top" alt="{{ pet.description }}" height="auto" width="auto">
                                {% else %}
                                    <img src="/media/resources/no_image.jpg" width="100%" height="auto" class="rounded" alt="{{ pet.name }}">
                                {% endif %}
        
                            <div class="card-body">
                                <h5 class="card-title">{{ pet.name }}</h5>
                                <p class="card-text">{{ pet.description }}</p>
                            </div>
                            <div class="card-footer d-flex justify-content-between">
                                <ul class="list-group list-group-flush w-100">
                                    <li class="list-group-item w-100">
                                        <small class="text-muted">{{ pet.create_at }}</small>
                                    </li>
                                    <li class="list-group-item w-100">
                                        <small class="text-muted">{{ pet.age }} años</small>
                                    </li>
                                    <li class="list-group-item w-100">
                                        <small class="text-muted">{{ pet.specie }}</small>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </a>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock content %}