adoptame/adoptame/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from core.views import index, contact

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('', include('core.urls')),
    path('pets/', include('pet.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('chat/', include('chat.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

adoptame/chat/urls.py
from django.urls import path
from . import views

app_name='chat'
urlpatterns = [
    path('', views.inbox, name='inbox'),
    path('<int:pk>/', views.detail, name='detail'),
    path('new/<int:pet_pk>/', views.new_chat, name='new'),
]

adoptame/core/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views
from .forms import LoginForm

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact' ),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('404/', views.error_404, name='404')
]

adoptame/dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name='index')
]

adoptame/pet/urls.py
from django.urls import path
from . import views

app_name = 'pet'

urlpatterns = [
    path('', views.pets, name='pets'),
    path('new/', views.new, name='new'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),
    path('get-races/', views.get_races, name='getRaces'),
]

adoptame/user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    path('index', views.index, name='index'),
    path('<int:pk>/edit/', views.edit, name='edit'),
    path('<int:pk>/delete/', views.delete, name='delete'),
]

adoptame/core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from user.models import PetOwner as User

class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')
    FORMCLASS ='col-12 rounded-3'

    username = forms.CharField(widget=forms.TextInput(attrs={
                                'placeholder': 'Tu nombre de usuario',
                                'class': FORMCLASS,
                                'style': 'height:3em'
                                }))
    email = forms.CharField(widget=forms.EmailInput(attrs={
                                'placeholder': 'Tu dirección de correo',
                                'class': FORMCLASS,
                                'style': 'height:3em'
                                }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
                                'placeholder': 'Tu contraseña',
                                'class': FORMCLASS,
                                'style': 'height:3em'
                                }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
                                'placeholder': 'Repite tu contraseña',
                                'class': FORMCLASS,
                                'style': 'height:3em'
                                }))


class LoginForm(AuthenticationForm):
    FORMCLASS ='col-12 rounded-3'

    username = forms.CharField(widget=forms.TextInput(attrs={
                                'placeholder': 'Tu nombre de usuario',
                                'class': FORMCLASS,
                                'style': 'height:3em'
                                }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
                                'placeholder': 'Tu contraseña',
                                'class': FORMCLASS,
                                'style': 'height:3em'
                                }))

adoptame/core/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from pet.models import Specie, Pet
from .forms import SignupForm

def index(request):
    pets = Pet.objects.filter(adopted=False)
    species = Specie.objects.all()

    context = {
        'species': species,
        'pets': pets
    }

    return render(request, 'core/index.html', context)

def contact(request):
    return render(request, 'core/contact.html')

def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)

        if form.is_valid():
            form.save()

            return redirect('/login/')
    else:
        form = SignupForm()

    return render(request, 'core/signup.html', {'form': form})

@login_required
def logout_view(request):
    logout(request)
    pets = Pet.objects.filter(adopted=False)
    species = Specie.objects.all()

    context = {
        'species': species,
        'pets': pets
    }

    return render(request, 'core/index.html', context)

def error_404(request):
    return render(request, 'core/404.html')

adoptame/core/templates/core/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    
    <link href="{% static 'fontawesomefree/css/fontawesome.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'fontawesomefree/css/brands.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'fontawesomefree/css/solid.css' %}" rel="stylesheet" type="text/css">

    <title>Adopta.me | {% block title %} {% endblock title %}</title>
</head>
<body class="d-flex flex-column min-vh-100 bg-light">
    <nav class="px-4 py-4 d-flex justify-content-between align-items-center border-bottom border-gray-200 bg-white">
        <a href="{% url 'core:index' %}" class="display-3 fw-bold text-decoration-none text-reset">Inicio</a>

        <div class="display-6">
            {% if user.is_superuser %}
            <a href="{% url 'user:index' %}" class="btn fs-3 fw-bold text-danger">Gestionar usuarios</a>
            {% endif %}
            <a href="{% url 'pet:new' %}" class="btn fs-3 fw-bold">Nueva Mascota</a>
            <a href="{% url 'pet:pets' %}" class="btn fs-3 fw-bold">Buscador</a>

            {% if request.user.is_authenticated %}
            <a href="{% url 'chat:inbox' %}" class="btn btn-primary">Mensajes</a>
            <a href="{% url 'dashboard:index' %}" class="btn btn-secondary"><i class="fa fa-user" aria-hidden="true"></i> Mis mascotas</a>
            <a href="{% url 'core:logout' %}" class="btn btn-danger"><i class="fa-solid fa-arrow-right-from-bracket"></i> Cerrar sesion</a>
            {% else %}
            <a href="{% url 'core:signup' %}" class="btn btn-primary">Registro</a>
            <a href="{% url 'core:login' %}" class="btn btn-secondary">Inicio de Sesión</a>
            {% endif %}
        </div>
    </nav>
    <div class="py-3 px-2 bg-light">
        {% block content %}
        {% endblock content %}
    </div>

    <footer class="mt-auto px-4 py-4 d-flex justify-content-between bg-dark">
        <div class="w-75 pr-5 ">
            <h3 class="mb-2 text-white">Sobre nosotros</h3>
            <p class="text-secondary">Jesus Abellan Garcia</p>
            <p class="text-secondary">jesusabellan97@gmail.com</p>
        </div>
        <div class="w-25">
            <h3 class="mb-2 text-white">Menu</h3>

            <ul class="my-2 px-0">
                <li><a href="{% url 'core:404' %}" class="link-info text-decoration-none">Sobre nosotros</a></li>
                <li><a href="{% url 'core:404' %} " class="link-info text-decoration-none">Privacidad</a></li>
                <li><a href="{% url 'core:404' %} " class="link-info text-decoration-none">Terminos de uso</a></li>
            </ul>
        </div>
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>

adoptame/core/templates/core/contact.html
{% extends "core/base.html" %}
{% block title %}
    Contacto
{% endblock title %}
{% block content %}
    <h1>Contáctanos</h1>
{% endblock content %}

adoptame/core/templates/core/index.html
{% extends "core/base.html" %}
{% block title %}
    Bienvenido
{% endblock title %}
{% block content %}
    <div class="px-3 py-5 bg-light rounded">
        <h2 class="mb-5 display-3 text-center">Nuevas Mascotas</h2>
    </div>
    <div class="row bg-light">
        {% for pet in pets %}
            <a href="{% url 'pet:detail' pet.id %}" class="col-sm-3 text-decoration-none text-reset">
                <div class="card h-100">
                        {% if pet.image %}
                            <img src="{{ pet.image.url }}" class="card-img-top" alt="{{ pet.description }}" height="auto" width="auto">
                        {% else %}
                            <img src="/media/resources/no_image.jpg" width="100%" height="auto" class="rounded" alt="{{ pet.name }}">
                        {% endif %}

                    <div class="card-body">
                        <h5 class="card-title">{{ pet.name }}</h5>
                        <p class="card-text">{{ pet.description }}</p>
                    </div>
                    <div class="card-footer d-flex justify-content-between">
                        <ul class="list-group list-group-flush w-100 rounded">
                            <li class="list-group-item w-100">
                                <small class="text-muted"> {{ pet.created_by }} | {{ pet.create_at }}{% if pet.created_by.is_shelter %} | <i class="fa-solid fa-house-circle-check" style="color:green"></i> {% endif %}</small>
                            </li>
                            <li class="list-group-item w-100">
                                <small class="text-muted">{{ pet.age }} años</small>
                            </li>
                            <li class="list-group-item w-100">
                                <small class="text-muted">{{ pet.specie }}</small>
                            </li>
                        </ul>
                    </div>
                </div>
            </a>
        {% endfor %}
    </div>
{% endblock content %}

adoptame/core/templates/core/login.html
{% extends "core/base.html" %}

{% block title %}
Inicio de Sesión
{% endblock title %}

{% block content %}
<div class="w-25 my-3 mx-auto bg-white p-3 border border-dark rounded-3">
    <h2 class="mb-3">Inicio de sesion</h2>

    <form method="post" action="." class='container'>
        {% csrf_token %}
        <div class="mb-3 row">
            <label class="col-8 ">Nombre de usuario:</label>
            {{ form.username }}
        </div>
        <div class="mb-3 row">
            <label class="col-8">Contraseña: </label>
            {{ form.password }}
        </div>

        {% if form.errors or form.non_field_erros %}
            <div class="mb-2 p-3 bg-error rounded-3">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}
                {{ form.non_field_erros }}
            </div>
        {% endif %}
        <button class="btn btn-primary px-4 py-3">Registrate</button>
    </form>
</div>
{% endblock content %}

adoptame/core/templates/core/signup.html
{% extends "core/base.html" %}

{% block title %}
Registro
{% endblock title %}

{% block content %}
<div class="w-25 my-3 mx-auto bg-white p-3 border border-dark rounded-3">
    <h2 class="mb-3">Registro</h2>

    <form method="post" action="." class="container">
        {% csrf_token %}
        <div class="mb-3 row">
            <label class="col-8 ">Nombre de usuario:</label>
            {{ form.username }}
        </div>
        <div class="mb-3 row">
            <label class="col-8">Email:</label>
            {{ form.email }}
        </div>
        <div class="mb-3 row">
            <label class="col-8">Contraseña: </label>
            {{ form.password1 }}
        </div>
        <div class="mb-3 row">
        <label class="col-8">Repite la contraseña:</label>
            {{ form.password2 }}
        </div>

        {% if form.errors or form.non_field_erros %}
            <div class="mb-2 p-3 bg-error rounded-3">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}
                {{ form.non_field_erros }}
            </div>
        {% endif %}
        <button class="btn btn-primary px-4 py-3">Registrate</button>
    </form>
</div>
{% endblock content %}