adoptame/adoptame/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from core.views import index, contact

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('', include('core.urls')),
    path('pets/', include('pet.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('chat/', include('chat.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

adoptame/pet/urls.py
from django.urls import path
from . import views

app_name = 'pet'

urlpatterns = [
    path('', views.pets, name='pets'),
    path('new/', views.new, name='new'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),
    path('get-races/', views.get_races, name='getRaces'),
]

adoptame/user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    path('index', views.index, name='index'),
    path('<int:pk>/edit/', views.edit, name='edit'),
    path('<int:pk>/delete/', views.delete, name='delete'),
]

adoptame/user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class PetOwner(AbstractUser):
    username = models.CharField(max_length=100, unique=True)
    email = models.EmailField(unique=True)
    password = models.CharField(max_length=100)

    is_shelter = models.BooleanField(default=False)

    def __str__(self):
        return self.username


# Create your models here.

adoptame/user/forms.py
from django import forms
from .models import PetOwner


class EditPetOwnerForm(forms.ModelForm):
    class Meta:
        model = PetOwner
        fields = ('username', 'email', 'is_shelter')
    FORMCLASS ='col-12 rounded-3'

    username = forms.CharField(widget=forms.TextInput(attrs={
                                'placeholder': 'Tu nombre de usuario',
                                'class': FORMCLASS,
                                'style': 'height:3em'
                                }))
    email = forms.CharField(widget=forms.EmailInput(attrs={
                                'placeholder': 'Tu dirección de correo',
                                'class': FORMCLASS,
                                'style': 'height:3em'
                                }))
    is_shelter = forms.BooleanField(widget=forms.CheckboxInput(attrs={
                                    'class': 'form-check-input'
                                    }))

adoptame/user/views.py
from django.contrib.auth.decorators import user_passes_test
from django.shortcuts import render, get_object_or_404, redirect
from .models import PetOwner
from .forms import EditPetOwnerForm

@user_passes_test(lambda u: u.is_superuser)
def index(request):
    users = PetOwner.objects.all()

    context = {
        'users': users
    }

    return render(request, 'user/index.html', context)


@user_passes_test(lambda u: u.is_superuser)
def edit(request, pk):
    pet = get_object_or_404(PetOwner, pk=pk)

    if request.method == 'POST':
        form = EditPetOwnerForm(request.POST, request.FILES, instance=pet)

        if form.is_valid():
            form.save()

            return redirect('user:index')
    else:
        form = EditPetOwnerForm(instance=pet)

    return render(request, 'user/form.html', {'form': form, 'title': f'Editar {PetOwner.username}' })

@user_passes_test(lambda u: u.is_superuser)
def delete(request, pk):
    pet = get_object_or_404(PetOwner, pk=pk)
    pet.delete()

    return redirect('user:index')

adoptame/user/templates/user/form.html
{% extends "core/base.html" %}

{% block title %}
Registro
{% endblock title %}

{% block content %}
<div class="w-25 my-3 mx-auto bg-white p-3 border border-dark rounded-3">
    <h2 class="mb-3">{{ title }}</h2>

    <form method="post" action="." class="container">
        {% csrf_token %}
        <div class="mb-3 row">
            <label class="col-8 ">Nombre de usuario:</label>
            {{ form.username }}
        </div>
        <div class="mb-3 row">
            <label class="col-8">Email:</label>
            {{ form.email }}
        </div>
        <div class="mb-3 row">
            <label class="form-check-label col-5" for="id_is_shelter">¿Es un refugio?</label>
                {{ form.is_shelter }}
        </div>

        {% if form.errors or form.non_field_erros %}
            <div class="mb-2 p-3 bg-error rounded-3">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}
                {{ form.non_field_erros }}
            </div>
        {% endif %}
        <button class="btn btn-primary px-4 py-3">Editar</button>
    </form>
</div>
{% endblock content %}

adoptame/user/templates/user/index.html
{% extends "core/base.html" %}

{% block title %}Gestion de usuarios {% endblock title %}

{% block content %}

<ul class="list-group list-group-flush w-100">
{% for user in users %}
    <li class="list-group-item w-100 d-flex rounded border py-3 mb-2">
        <div class="col-4">
            {{ user }}
        </div>
        <div class="col-4">
            {{ user.date_joined }}{% if user.is_shelter %} | <i class="fa-solid fa-house-circle-check" style="color:green"></i> {% endif %}
        </div>
        <div class="col-4">
            <a href="{% url 'user:edit' user.id %}" class="btn btn-success">Editar</a>
            <a href="{% url 'user:delete' user.id %}" class="btn btn-danger">Borrar</a>
            
        </div>
    </li>
{% endfor %}
</ul>
{% endblock content %}